# Generated by Django 5.1.6 on 2025-03-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_id', models.IntegerField()),
                ('Customer_id', models.CharField(max_length=14)),
                ('Customer_name', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=6)),
                ('Transaction_type', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Transaction_Timestamp', models.DateTimeField()),
                ('IP_Address', models.GenericIPAddressField()),
                ('avg_spending', models.CharField(max_length=6)),
                ('avg_transaction_count', models.CharField(max_length=100)),
                ('Last_transaction_time', models.DateTimeField()),
            ],
        ),
    ]
