# Generated by Django 5.1.5 on 2025-03-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=12)),
                ('amount', models.CharField(max_length=6)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('transactionType', models.CharField(max_length=9)),
                ('IP_address', models.GenericIPAddressField(blank=True, null=True)),
                ('transactionStatus', models.CharField(max_length=15)),
                ('fraudScore', models.IntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
