# Generated by Django 5.1.5 on 2025-03-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='customerId',
            field=models.CharField(max_length=14),
        ),
    ]
