# Generated by Django 5.1.7 on 2025-03-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerId',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customerId',
            field=models.CharField(max_length=14),
        ),
    ]
