# Generated by Django 5.1.7 on 2025-03-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_customer_customerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=29, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=29, null=True),
        ),
    ]
