# Generated by Django 5.1.6 on 2025-03-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_data',
            fields=[
                ('transaction_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=14)),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('transaction_timestamp', models.DateTimeField()),
                ('hour_of_day', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('avg_spending', models.FloatField()),
                ('avg_transaction_count', models.IntegerField()),
                ('last_transaction_time', models.DateTimeField()),
                ('fraud_score', models.FloatField(blank=True, null=True)),
                ('fraud_label', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
